// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qziltegbxmsmnsifuast.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6aWx0ZWdieG1zbW5zaWZ1YXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMzk4MTEsImV4cCI6MjA3NTcxNTgxMX0.U27S9UnuzRE0EbubJR2LBa10sDDzSLMD6kfHS7Meg5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});